/*
 * Ctx.java
 *
 * Created on __DATE__, __TIME__
 */

package sm.clagenna.crypt.view;

/**
 * 
 * @author __USER__
 */
public class Ctx extends javax.swing.JPanel {
  private static final long serialVersionUID = -4897961737402717849L;
  private IRsa              irsa;
  private boolean           m_bNoEvent;

  private String            m_szLabel;
  private Long              m_lValue;

  /** Creates new form Ctx */
  public Ctx() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // GEN-BEGIN:initComponents
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    lbl = new javax.swing.JLabel();
    tx = new javax.swing.JTextField();

    setLayout(new java.awt.BorderLayout());

    lbl.setText("label");
    add(lbl, java.awt.BorderLayout.PAGE_START);

    tx.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    tx.setText("0");
    tx.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txActionPerformed(evt);
      }
    });
    add(tx, java.awt.BorderLayout.CENTER);
  }// </editor-fold>

  // GEN-END:initComponents

  public void setLabel(String label) {
    m_szLabel = label;
    lbl.setText(m_szLabel);
  }

  public String getLabel() {
    return m_szLabel;
  }

  public void setVal(Long val) {
    setNoEvent(true);
    try {
      m_lValue = val;
      if (m_lValue != null)
        tx.setText(toMoney(m_lValue));
      else
        tx.setText("");
    } finally {
      setNoEvent(false);
    }
  }

  public Long getVal() {
    String sz = tx.getText();
    if (sz == null || sz.length() == 0)
      m_lValue = Long.valueOf(0);
    else {
      sz = sz.replaceAll("\\.", "");
      m_lValue = Long.valueOf(sz);
    }
    return m_lValue;
  }

  public void setIrsa(IRsa irsa) {
    this.irsa = irsa;
  }

  public IRsa getIrsa() {
    return irsa;
  }

  public void setNoEvent(boolean m_bNoEvent) {
    this.m_bNoEvent = m_bNoEvent;
  }

  public boolean isNoEvent() {
    return m_bNoEvent;
  }

  // GEN-END:initComponents

  private void txActionPerformed(java.awt.event.ActionEvent evt) {
    if (isNoEvent())
      return;
    Long ll = getVal();
    if (irsa != null)
      irsa.setValue(m_szLabel, ll);
  }

  private String toMoney(Long vv) {
    String sz = vv.toString();
    int n = sz.length() - 1;
    StringBuilder sb = new StringBuilder();
    for (char c : sz.toCharArray()) {
      sb.append(c);
      if (n > 0 && (n-- % 3) == 0)
        sb.append('.');
    }
    return sb.toString();
  }

  // GEN-BEGIN:variables
  // Variables declaration - do not modify
  private javax.swing.JLabel     lbl;
  private javax.swing.JTextField tx;
  // End of variables declaration//GEN-END:variables

}
