package sm.ciscoop.crypt.view;

import java.util.List;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author __USER__
 */
public class Cbx extends javax.swing.JPanel {
  private static final long serialVersionUID = -1248740956687877783L;

  private String            m_szLabel;
  private Long              m_lValue;
  private List<Long>        lista;
  private IRsa              irsa;
  private boolean           m_bNoEvent;

  /** Creates new form Cbx */
  public Cbx() {
    initComponents();
    setNoEvent(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  //GEN-BEGIN:initComponents
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    lbl = new javax.swing.JLabel();
    cb = new javax.swing.JComboBox<Long>();

    lbl.setText("Lbl");

    cb.setPreferredSize(new java.awt.Dimension(120, 22));
    cb.addActionListener(new java.awt.event.ActionListener() {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup().addComponent(lbl).addContainerGap(191, Short.MAX_VALUE))
        .addComponent(cb, 0, 207, Short.MAX_VALUE));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup().addComponent(lbl)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE)));
  }// </editor-fold>
   //GEN-END:initComponents

  private void cbActionPerformed(java.awt.event.ActionEvent evt) {
    if (isNoEvent())
      return;
    Long ll = getValue();
    if (irsa != null)
      irsa.setValue(this.getName(), ll);
  }

  public void setLabel(String sz) {
    m_szLabel = sz;
    lbl.setText(m_szLabel);
  }

  public String getLabel() {
    return lbl.getText();
  }

  @SuppressWarnings("unchecked")
  public void setValue(Long vv) {
    m_lValue = vv;
    DefaultComboBoxModel<Long> cbm = (DefaultComboBoxModel<Long>) cb.getModel();
    cbm.setSelectedItem(m_lValue);
  }

  @SuppressWarnings("unchecked")
  public Long getValue() {
    DefaultComboBoxModel<Long> cbm = (DefaultComboBoxModel<Long>) cb.getModel();
    m_lValue = (Long) cbm.getSelectedItem();
    return m_lValue;
  }

  @SuppressWarnings("unchecked")
  public void setLista(List<Long> pl) {
    lista = pl;
    setNoEvent(true);
    try {
      DefaultComboBoxModel<Long> cbm = (DefaultComboBoxModel<Long>) cb.getModel();
      cbm.removeAllElements();
      for (Long ll : lista) {
        cbm.addElement(ll);
      }
    } finally {
      setNoEvent(false);
    }
  }

  public List<Long> getLista() {
    return lista;
  }

  public void setIrsa(IRsa irsa) {
    this.irsa = irsa;
  }

  public IRsa getIrsa() {
    return irsa;
  }

  public void setNoEvent(boolean m_bNoEvent) {
    this.m_bNoEvent = m_bNoEvent;
  }

  public boolean isNoEvent() {
    return m_bNoEvent;
  }

  //GEN-BEGIN:variables
  // Variables declaration - do not modify
  private javax.swing.JComboBox cb;
  private javax.swing.JLabel    lbl;
  // End of variables declaration//GEN-END:variables

}
