/*
 * PanChoice.java
 *
 * Created on __DATE__, __TIME__
 */

package sm.ciscoop.crypt.view;

import java.awt.Cursor;
import java.util.List;

import sm.ciscoop.crypt.primi.PrimiFactory;
import sm.ciscoop.crypt.rsa.RsaObj;

/**
 * 
 * @author __USER__
 */
public class PanChoice extends javax.swing.JPanel implements IRsa {
  private static final long serialVersionUID = 1L;

  private IRsa              m_irsa;
  private RsaObj            rsa;
  Long                      m_lP, m_lQ, m_lPQ;

  /** Creates new form PanChoice */
  public PanChoice() {
    initComponents();
    miaInit();
  }

  private void miaInit() {
    setRsa(new RsaObj());
    cbP.setIrsa(this);
    cbQ.setIrsa(this);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // GEN-BEGIN:initComponents
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    panBottoni = new javax.swing.JPanel();
    txMinPrimo = new sm.ciscoop.crypt.view.Ctx();
    txQtaPrimi = new sm.ciscoop.crypt.view.Ctx();
    txMaxPrimo = new sm.ciscoop.crypt.view.Ctx();
    btGenPrimi = new javax.swing.JButton();
    cbP = new sm.ciscoop.crypt.view.Cbx();
    cbQ = new sm.ciscoop.crypt.view.Cbx();
    txPQ = new sm.ciscoop.crypt.view.Ctx();
    txE = new sm.ciscoop.crypt.view.Ctx();
    txD = new sm.ciscoop.crypt.view.Ctx();
    jButton1 = new javax.swing.JButton();
    txProbes = new sm.ciscoop.crypt.view.Ctx();

    panBottoni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txMinPrimo.setLabel("Min Primo");
    panBottoni.add(txMinPrimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

    txQtaPrimi.setLabel("Qta Primi");
    panBottoni.add(txQtaPrimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, -1));

    txMaxPrimo.setLabel("Max Primo");
    panBottoni.add(txMaxPrimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, -1));

    btGenPrimi.setText("Primi");
    btGenPrimi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btGenPrimiActionPerformed(evt);
      }
    });
    panBottoni.add(btGenPrimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

    cbP.setLabel("Val P");
    cbP.setName("P");
    panBottoni.add(cbP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

    cbQ.setLabel("Val Q");
    cbQ.setName("Q");
    panBottoni.add(cbQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 100, -1));

    txPQ.setLabel("PQ");
    panBottoni.add(txPQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 80, 40));

    txE.setLabel("Val E");
    panBottoni.add(txE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, -1));

    txD.setLabel("Val D");
    panBottoni.add(txD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, -1));

    jButton1.setText("Calcola");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    panBottoni.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

    txProbes.setLabel("Probes");
    panBottoni.add(txProbes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 80, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panBottoni,
        javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panBottoni,
        javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE));
  }// </editor-fold>

  // GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void btGenPrimiActionPerformed(java.awt.event.ActionEvent evt) {
    PrimiFactory pf = getRsa().getPrimiFactory();
    Long min = txMinPrimo.getVal();
    Long qta = txQtaPrimi.getVal();
    Long max = txMaxPrimo.getVal();
    if ( (qta == null || qta.longValue() == 0) && (max == null || max.longValue() == 0))
      return;

    if (qta.longValue() > 4 && min == 0)
      pf.buildPrimi(qta.intValue());
    else if ( min > 2)
      pf.buildPrimi(min, qta);
    else
      pf.buildPrimi(qta.intValue());
    List<Long> ls = pf.getList();
    cbP.setLista(ls);
    cbQ.setLista(ls);
  }

  /**
   * @param args
   *          the command line arguments
   */
  // public static void main(String args[]) {
  // java.awt.EventQueue.invokeLater(new Runnable() {
  // public void run() {
  // PanChoice dialog = new PanChoice(new javax.swing.JFrame(), true);
  // dialog.addWindowListener(new java.awt.event.WindowAdapter() {
  // public void windowClosing(java.awt.event.WindowEvent e) {
  // System.exit(0);
  // }
  // });
  // dialog.setVisible(true);
  // }
  // });
  // }

  // GEN-BEGIN:variables
  // Variables declaration - do not modify
  private javax.swing.JButton       btGenPrimi;
  private sm.ciscoop.crypt.view.Cbx cbP;
  private sm.ciscoop.crypt.view.Cbx cbQ;
  private javax.swing.JButton       jButton1;
  private javax.swing.JPanel        panBottoni;
  private sm.ciscoop.crypt.view.Ctx txD;
  private sm.ciscoop.crypt.view.Ctx txE;
  private sm.ciscoop.crypt.view.Ctx txMaxPrimo;
  private sm.ciscoop.crypt.view.Ctx txMinPrimo;
  private sm.ciscoop.crypt.view.Ctx txPQ;
  private sm.ciscoop.crypt.view.Ctx txProbes;
  private sm.ciscoop.crypt.view.Ctx txQtaPrimi;

  // End of variables declaration//GEN-END:variables

  @Override
  public boolean setValue(String id, Long lv) {
    if (id == null)
      return false;

    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    System.out.println(String.format("setVal[%s]=%d", id, lv));

    try {
      if (id.equals(cbP.getName()))
        m_lP = lv;
      if (id.equals(cbQ.getName()))
        m_lQ = lv;
      if (m_lP != null && m_lQ != null) {
        getRsa().setP(m_lP);
        getRsa().setQ(m_lQ);
      }
      txPQ.setVal(getRsa().getPQ());
      txE.setVal(getRsa().getE());
      txD.setVal(getRsa().getD());
      txProbes.setVal(getRsa().getProbes());
      if (m_irsa != null)
        m_irsa.setValue(id, lv);
    } finally {
      setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }
    return false;
  }

  /**
   * @param rsa
   *          the rsa to set
   */
  public void setRsa(RsaObj rsa) {
    this.rsa = rsa;
  }

  /**
   * @return the rsa
   */
  public RsaObj getRsa() {
    return rsa;
  }

  public void setIrsa(IRsa m_irsa) {
    this.m_irsa = m_irsa;
  }

  public IRsa getIrsa() {
    return m_irsa;
  }

  // @Override
  // public boolean setP(Long pP) {
  // m_lP = pP;
  // if (m_lQ != null)
  // m_lPQ = Long.valueOf(m_lP.longValue() * m_lQ.longValue());
  // txPQ.setVal(m_lPQ);
  // return false;
  // }
  //
  // @Override
  // public boolean setQ(Long pQ) {
  // m_lQ = pQ;
  // if (m_lP != null)
  // m_lPQ = Long.valueOf(m_lP.longValue() * m_lQ.longValue());
  // txPQ.setVal(m_lPQ);
  // return false;
  // }

}
