/*
 * MainFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package test.view;

import java.awt.BorderLayout;

import sm.clagenna.crypt.view.PanChoice;

/**
 * 
 * @author __USER__
 */
public class MainFrame extends javax.swing.JFrame {
  private static final long serialVersionUID = -412453710813071888L;

  /** Creates new form MainFrame */
  public MainFrame() {
    initComponents();
    miaInit();
  }

  private void miaInit() {
    PanChoice pan = new PanChoice();
    panTestTutti.add(pan, BorderLayout.CENTER);
    pack();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  //GEN-BEGIN:initComponents
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    panTestTutti = new javax.swing.JPanel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenu2 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    panTestTutti.setLayout(new java.awt.BorderLayout());
    getContentPane().add(panTestTutti, java.awt.BorderLayout.CENTER);

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>
  //GEN-END:initComponents

  /**
   * @param args
   *          the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainFrame().setVisible(true);
      }
    });
  }

  //GEN-BEGIN:variables
  // Variables declaration - do not modify
  private javax.swing.JMenu    jMenu1;
  private javax.swing.JMenu    jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPanel   panTestTutti;
  // End of variables declaration//GEN-END:variables

}
